# Generated by Django 4.1.2 on 2022-11-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AugTask',
            fields=[
                ('taskId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('dataset', models.CharField(max_length=255)),
                ('augType', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'AugTask',
            },
        ),
        migrations.CreateModel(
            name='dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('num', models.IntegerField()),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dataset',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('modelId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('modelType', models.CharField(max_length=255)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Model',
            },
        ),
    ]
