# Generated by Django 4.1.2 on 2022-11-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='augtask',
            name='desc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
