# Generated by Django 4.1.2 on 2022-11-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augsys', '0002_augtask_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeeptestParams',
            fields=[
                ('taskName', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tranXmin', models.IntegerField(null=True)),
                ('tranXmax', models.IntegerField(null=True)),
                ('tranYmin', models.IntegerField(null=True)),
                ('scaleXmin', models.IntegerField(null=True)),
                ('scaleXmax', models.IntegerField(null=True)),
                ('scaleYmin', models.IntegerField(null=True)),
                ('scaleYmax', models.IntegerField(null=True)),
                ('degreeMin', models.IntegerField(null=True)),
                ('degreeMax', models.IntegerField(null=True)),
                ('biasMin', models.IntegerField(null=True)),
                ('biasMax', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'DeepParams',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('taskName', models.CharField(max_length=255)),
                ('strategy', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'strategy',
            },
        ),
        migrations.RenameField(
            model_name='augtask',
            old_name='dataset',
            new_name='fileType',
        ),
        migrations.RemoveField(
            model_name='augtask',
            name='taskId',
        ),
        migrations.AddField(
            model_name='augtask',
            name='num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='augtask',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
