# Generated by Django 4.1.2 on 2022-11-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augsys', '0003_deeptestparams_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deeptestparams',
            name='tranYmax',
            field=models.IntegerField(null=True),
        ),
    ]
