# Generated by Django 4.1.2 on 2022-11-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augsys', '0006_alter_augtask_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='augtask',
            name='times',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
