# Generated by Django 4.1.2 on 2022-11-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('augsys', '0008_methods'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='methods',
            table='Methods',
        ),
    ]
