# Generated by Django 4.1.2 on 2022-11-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augsys', '0009_alter_methods_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'instance',
            },
        ),
    ]
