# Generated by Django 4.1.2 on 2022-12-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augsys', '0010_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictTask',
            fields=[
                ('taskName', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('taskDesc', models.CharField(max_length=500, null=True)),
                ('dataset', models.CharField(max_length=255)),
                ('num', models.IntegerField()),
                ('model', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
