# Generated by Django 4.1.2 on 2022-12-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('augsys', '0011_predicttask'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='predicttask',
            table='predictTask',
        ),
    ]
