# Generated by Django 4.1.2 on 2022-12-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augsys', '0013_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='setType',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
