# Generated by Django 4.1.2 on 2023-03-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augsys', '0014_testcase_settype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('taskName', models.CharField(max_length=255)),
                ('metric', models.CharField(max_length=255)),
                ('threshold', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'threshold',
            },
        ),
    ]
