# Generated by Django 4.1.2 on 2023-05-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augsys', '0016_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataName', models.CharField(max_length=255)),
                ('r1', models.CharField(max_length=255)),
                ('r2', models.CharField(max_length=255)),
                ('r3', models.CharField(max_length=255)),
                ('r4', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'metaResult',
            },
        ),
    ]
